### ISSUE TITLE
I would like to move this repo out of Enqueue org

### ISSUE THREAD

**Issue by makasim** [sroze/messenger-adapter#62]
The reason is: 

Enqueue team does not support the adapter project so I'd love to make it clear for everyone that this projected has nothing to do with this org.

**Comment by Steveb-p** [comment]
It's kind of sad, buti understand where you're coming from. Unfortunately there is not really any entity that can take it on. It's either you or Symfony.

I doubt Symfony folks will take under their name since it's directly tied to Enqueue. They do endorse the usage of messenger-adapter in their documentation, but that's pretty much it :/

**Comment by weaverryan** [comment]
I understand your point of view. Indeed, Symfony will not take it under their name, and I'm not willing to take it under mine either (I also need to be realistic about what I have the capacity to "own").

If someone else is willing to take it under their name and continue to maintain it (I can offer some help with that), great.

**Comment by sroze** [comment]
We can move it back under my name for the time being but it would be great
to have it maintain by a pre-defined set of people :)

**Comment by makasim** [comment]
I've just give you @sroze owner permission. take it from here.
